### ISSUE TITLE
Ligatures don't work

### ISSUE THREAD

**Issue by aDotInTheVoid** [WTy-2/spec#4]
but also, I don't think their a good idea for the spec, where we want to unambiguously communicate what the source code is doing.

**Comment by NathanielB123** [comment]
On my laptop they appear to work fine in Edge and Chrome, but yeah at least in Firefox it looks like they are broken (I think the code blocks just straight-up using a different font...). Personally I think ligatures help make a lot of the operators look much nicer `/\`, `<<=`, `<=:` etc are all really ugly, but the point about communicating what the source code is doing is good. I wonder if it can be turned into an option somehow (similar to configuring the colour theme).

Side note: I am now "watching" the repository and so hopefully will see and respond to these issues quicker. Not sure why I wasn't before.

**Comment by NathanielB123** [comment]
Ligature toggle button added in https://github.com/WTy-2/spec/commit/4d24de01373f887f9355af361657a2c0d2d1614a (very janky, but it works)

I think Firefox should be "fixed" now as well. For some reason it doesn't want to display my build of the font but it is happy to take one from Google, which is pretty similar (lone `|`s are made taller, which I'm not a massive fan of, but that's about my only problem with it)
